# Treatment Effects

**Learning objectives:**

- Define effect size metrics
- Discuss workflows


<details>
<summary>Session Info</summary>

```{r}
sessionInfo()
```

</details>


## For Whom the Effect Holds

**Heterogenous treatment effort** on an outcome for which the effect itself varies across the population.

* Sample set, but hoping for **external validity**
* Perhaps make a *distribution of effects*
* Focus on *identification*


## Different Averages

<details>
<summary>ATE</summary>

**Average Treatment Effect**

* If we impose treatment on everyone
* Usually what we want to estimate

</details>

<details>
<summary>CATE</summary>

**Conditional Average Treatment Effect**

* If subsetting the groups
* Doesn't generalize to everyone

</details>

<details>
<summary>ATT</summary>

**Average Treatment on the Treated**

</details>

<details>
<summary>ATUT</summary>

**Average Treatment on the Untreated**

</details>

<details>
<summary>Marginal treatment effect</summary>

The treatment effect of the next individual that would be treated if treatment were expanded.

</details>

<details>
<summary>Weighted average treatment effect</summary>

A treatment effect average where each individual’s treatment effect is weighted differently.

</details>

<details>
<summary>Variance-weighted average treatment effect</summary>

A treatment effect average where each individual’s treatment effect is weighted based on how much variation there is in their treatment variable, after closing back doors.

</details>


## I Just Want an ATE

> Which treatment variation do we allow to count

Rules of Thumb (do not apply 100 percent of the time)

1. True randomization $\rightarrow$ ATE
2. Randomization in a group $\rightarrow$ CATE
3. Closed back doors $\rightarrow$ weighted average treatment effect
4. Assuming treatment on untreated $\rightarrow$ ATT
5. Isolate exogenous variable $\rightarrow$ LATE

(Słoczyński, 2022)

* Comparing treated to *counterfactual* outcomes

    * More treated people, more represents ATUT


## Who Cares?

> We want to know what will happen if we intervene

* Understanding not just the overall effect
* Who that effect is for


## Meeting Videos {-}

### Cohort 1 {-}

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
