--- 
title: "The Effect: An Introduction to Research Design and Causality Book Club"
author: "The Data Science Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-effect
description: "This website is the product of the Data Science Learning Community's The Effect: An Introduction to Research Design and Causality Book Club."
---

# Introduction {-}

This is a companion for the book[_The Effect: An Introduction to Research Design and Causality_](https://theeffectbook.net/index.html) by Nick Huntington-Klein (copyright January 5, 2022).

-  These are **shared slides!**
   -  Developed by the [Data Science Learning Community](https://dslc.io).
   -  [Join the community](https://dslc.io/join) to participate.
   -  Available at [dslc.io/effect](https://dslc.io/effect).
-  We follow the [Data Science Learning Community Code of Conduct](https://dslc.io/conduct).

## Book club meetings {-}

-  [Volunteer leads discussion of a chapter](https://docs.google.com/spreadsheets/d/1z1sphmX9HZFs8TUz3eMLacOxckwonnWrmsBQqlNY2FI/edit?usp=sharing)
   -  **This is the best way to learn the material.**
-  Presentations: 
   -  Review of material
   -  Questions you have
   -  Maybe live demo
-  More info about editing: [this github repo](https://github.com/r4ds/bookclub-rpkgs).
-  Recorded, available on the [DSLC.video Community YouTube Channel](https://dslc.video).
-  **Camera** is **optional,** but **encouraged.**

## Pace {-}

-  Meet ***every*** week except holidays, etc
   -  We'll discuss even if presenter unavailable
-  Meetings = **1 hour.**
-  **Goal:** 1 chapter/week
-  Ok to split overwhelming chapters
-  Ok to combine short chapters
-  If we need to **slow down** and discuss, **let me know.**
   -  Most likely someone has the same question 
   -  We are all here to learn 

## Introductions {-}

If you feel comfortable sharing, unmute or raise your hand!

-  **Who** are you?
-  **Where** are you joining from?
-  **Previous clubs?** (DSLC or other)
-  **How long** have you been using R?
-  **What** are you most looking forward to learning?

## git and GitHub {-}

-  **Git/GitHub** (version control) = **valuable skill.**
   -  Discussed more in **Chapter 21.**
-  If you present, best to **integrate your materials** into this bookdown version.
-  You'll need a **GitHub account** to submit modifications.
-  **Full instructions** in [GitHub repository](https://github.com/r4ds/bookclub-rpkgs) ("repo").

## Group Question 1 {-}

(Submit answers in chat)

On a scale from 1 - 5, how familiar are you with using git for version control?

1 = Not at all familiar (a true beginner)

to

5 = Very familiar (use git everyday/can handle a merge conflict like a pro)

## Group Question 2 {-}

(Submit answers in chat)

On a scale from 1 - 5, how familiar are you with using GitHub?

1 = Not at all familiar (a true beginner)

to 

5 = Very familiar (I have GitHub account with repositories)

## Group Question 3 {-}

(Submit answers in chat)

On a scale from 1 - 5, how valuable would it be to devote a week to introducing git and GitHub?

1 = Not at all valuable

to 

5 = Very valuable

## git and GitHub Resources {-}

-  [Happy Git and GitHub for the useR](https://happygitwithr.com/)
-  [`usethis`'s pull request helpers](https://usethis.r-lib.org/articles/pr-functions.html)
-  [`git`'s documentation](https://git-scm.com/doc)
-  [MShiny Cohort 2 Introduction](https://www.youtube.com/watch?v=beOYuHG9Xng&list=PL3x6DOfs2NGjhwrYvdmrKRNcvXX7X6ldt)

## Learning objectives {-}

-  Students who study with LOs in mind ***retain more.***
-  **Tips:**
   -  "After today's session, you will be able to..."
   -  *Very* roughly **1 per section.**

## Today's learning objectives {-}

-  INSERT BOOK-SPECIFIC CONTENT STARTING HERE
-  AND THEN ADD SLIDES FOR CHAPTER 0 IF APPLICABLE
